[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test/unit"
remappings = [ "@chainlink/contracts/src/v0.8/=lib/chainlink-brownie-contracts/contracts/src/v0.8/" ]
ffi = true # enable FFI for foundry-devops - it allows us to run commands directly from the terminal
fs_permissions = [{ access = "read", path = "./broadcast" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

